name: DSMPBot
main: me.elJoa.dsmpbot.Bot
version: 2.0.1
author: elJoa
api-version: 1.17
depend: ["Plan", "spark"]
commands:
  informoneseventeen:
    description: LololStfuXD
    usage: /informoneseventeen
    permission: dsmpbot.informoneseventeen